M48
; DRILL file {KiCad (6.0.10)} date Sun Feb 26 13:23:59 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-02-26T13:23:59-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.10)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0984
%
G90
G05
T1
X1.4589Y-2.1024
X1.4589Y-5.3583
X10.1946Y-2.1024
X10.1946Y-5.3583
T0
M30
